import { useCallback, useEffect, useState } from "react";
import { Archive, Copy, LayoutDashboard, Plus, Search, Trash2, Pencil } from "lucide-react";
import { AppLink } from "../../components/AppLink";
import { navigateTo } from "../../lib/navigation";
import { boardApi } from "./api";
import type { BoardSummary } from "../../../../server/src/shared/boards";
import "./boards.css";

export function BoardLibrary({ accessToken, studentId, studentName = "Your", teacher = false, students = [] }: { accessToken: string; studentId?: string; studentName?: string; teacher?: boolean; students?: { id: string; fullName: string }[] }) {
  const teacherHome = teacher && !studentId;
  const [inviteStudentId, setInviteStudentId] = useState("");
  const [boards, setBoards] = useState<BoardSummary[]>([]), [search, setSearch] = useState(""), [sort, setSort] = useState("recent"), [archived, setArchived] = useState(false);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [dialog, setDialog] = useState<{ action: "create" | "rename" | "delete"; board?: BoardSummary } | null>(null), [title, setTitle] = useState("");
  const load = useCallback(async () => { try { setBoards(await boardApi(accessToken).list(studentId, teacher)); setError(""); } catch (error) { setError(error instanceof Error ? error.message : "Could not load boards."); } finally { setLoading(false); } }, [accessToken, studentId, teacher]);
  useEffect(() => { let active = true; boardApi(accessToken).list(studentId, teacher).then(boards => { if (active) { setBoards(boards); setError(""); } }).catch(error => { if (active) setError(error instanceof Error ? error.message : "Could not load boards."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [accessToken, studentId, teacher]);
  const boardHref = (id: string) => `/boards/${id}?returnTo=${encodeURIComponent(teacherHome ? "/teacher/boards" : teacher ? `/teacher/students?student=${studentId}&workspace=boards` : "/study-hall/shsat/boards")}`;
  const run = async (action: () => Promise<void>) => { setBusy(true); setError(""); try { await action(); setDialog(null); await load(); } catch (error) { setError(error instanceof Error ? error.message : "Could not update board."); } finally { setBusy(false); } };
  const visible = boards.filter(board => Boolean(board.archivedAt) === archived && board.title.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === "title" ? a.title.localeCompare(b.title) : sort === "oldest" ? a.updatedAt.localeCompare(b.updatedAt) : b.updatedAt.localeCompare(a.updatedAt));
  return <section className="board-library" aria-label={teacherHome ? "My teaching boards" : `${studentName} boards`}>
    <header><div><small>{teacherHome ? "Your teaching workspace" : teacher ? `${studentName}'s workspace` : "Shared learning workspace"}</small><h2>{teacherHome ? "My teaching boards" : teacher ? "Boards" : "My boards"}</h2><p>{teacherHome ? "Create a board, invite a student, and work together." : "Think, organize evidence, and work together with your teacher."}</p></div><button className="board-primary" disabled={busy} onClick={() => { setTitle("Untitled board"); setInviteStudentId(""); setDialog({ action: "create" }); }}><Plus size={16} /> New board</button></header>
    <div className="board-library-tools"><div className="board-library-tabs"><button aria-pressed={!archived} onClick={() => setArchived(false)}>Recent</button><button aria-pressed={archived} onClick={() => setArchived(true)}>Archived</button></div><label><Search size={16} /><input aria-label="Search boards" placeholder="Search boards" value={search} onChange={event => setSearch(event.target.value)} /></label><select aria-label="Sort boards" value={sort} onChange={event => setSort(event.target.value)}><option value="recent">Last edited</option><option value="title">Title</option><option value="oldest">Oldest first</option></select></div>
    {error && <p role="alert" className="board-error">{error} <button onClick={() => void load()}>Retry</button></p>}
    {loading ? <p>Loading boards…</p> : <div className="board-library-list">{visible.map(board => <article key={board.id}><LayoutDashboard size={20} /><AppLink href={boardHref(board.id)}><strong>{board.title}</strong><small>Edited {new Date(board.updatedAt).toLocaleString()} · {board.participants.map(person => person.name).join(" + ")}</small></AppLink><span className="board-role">{board.role}</span><div className="board-row-actions">{board.role !== "viewer" && !board.archivedAt && <button title="Duplicate board" aria-label={`Duplicate ${board.title}`} disabled={busy} onClick={() => void run(async () => { const copy = await boardApi(accessToken).duplicate(board.id); navigateTo(boardHref(copy.id)); })}><Copy size={15} /></button>}{board.role === "owner" && <><button title="Rename" aria-label={`Rename ${board.title}`} onClick={() => { setTitle(board.title); setDialog({ action: "rename", board }); }}><Pencil size={15} /></button><button title={archived ? "Restore board" : "Archive board"} aria-label={`${archived ? "Restore" : "Archive"} ${board.title}`} disabled={busy} onClick={() => void run(async () => { await boardApi(accessToken).manage(board, "archive", { archived: !archived }); })}><Archive size={15} /></button><button title="Delete" aria-label={`Delete ${board.title}`} onClick={() => { setTitle(""); setDialog({ action: "delete", board }); }}><Trash2 size={15} /></button></>}</div></article>)}{!visible.length && !error && <div className="board-empty"><LayoutDashboard size={28} /><strong>{archived ? "No archived boards" : "A space to think together"}</strong><p>{search ? "No boards match this search." : archived ? "Archived work will stay here." : "Create a board for notes, evidence, questions, and teacher feedback."}</p></div>}</div>}
    {dialog && <div className="board-modal-backdrop"><form role="dialog" aria-modal="true" aria-label={dialog.action === "create" ? "New board" : dialog.action === "rename" ? "Rename board" : "Delete board"} className="board-modal" onSubmit={event => { event.preventDefault(); void run(async () => {
      if (dialog.action === "create") { const created = await boardApi(accessToken).create(title, teacherHome ? inviteStudentId : studentId); navigateTo(boardHref(created.id)); }
      else if (dialog.action === "rename") await boardApi(accessToken).manage(dialog.board!, "rename", { title });
      else await boardApi(accessToken).manage(dialog.board!, "delete", { confirm: title });
    }); }}><h3>{dialog.action === "create" ? "New board" : dialog.action === "rename" ? "Rename board" : "Delete board"}</h3>{dialog.action === "delete" ? <p>Archive preserves student work. To remove this board, type <strong>{dialog.board!.title}</strong>. Deleted boards are retained for administrator recovery.</p> : <p>{teacherHome ? "Choose a student to invite as an editor. You will own the board." : teacher ? `This board will be shared with ${studentName} automatically.` : "Private to you until you invite a verified teacher."}</p>}{teacherHome && dialog.action === "create" && <label>Invite student<select required value={inviteStudentId} onChange={event => setInviteStudentId(event.target.value)}><option value="">Choose a student</option>{students.map(student => <option key={student.id} value={student.id}>{student.fullName}</option>)}</select></label>}<label>{dialog.action === "delete" ? "Confirm board title" : "Board title"}<input autoFocus required maxLength={200} value={title} onChange={event => setTitle(event.target.value)} onKeyDown={event => { if (event.key === "Escape") setDialog(null); }} /></label><footer><button type="button" disabled={busy} onClick={() => setDialog(null)}>Cancel</button><button className="board-primary" disabled={busy || !title.trim() || teacherHome && dialog.action === "create" && !inviteStudentId || dialog.action === "delete" && title !== dialog.board!.title}>{busy ? "Working…" : dialog.action === "create" ? "Create board" : dialog.action === "rename" ? "Rename" : "Delete board"}</button></footer>{error && <p role="alert">{error}</p>}</form></div>}
  </section>;
}
