import { createProsePassage } from "../formatters";
import type { ExamPassageSet, ExamQuestion } from "../types";

const scribeLikeAnEgyptianPassageText = " In ancient Egypt, literacy was the key to success. However, contrary to popular belief, not all Egyptian scribes understood hieroglyphs. Many relied instead on the simpler hieratic script for the multitude of everyday documents generated by the Egyptian bureaucracy.\n\nHieroglyphs—“the Words of God”—compose a writing system with more than 1,000 distinct characters, the meanings of which were lost for 1,500 years before they were deciphered by Jean-François Champollion in 1822. Including both ideograms (which convey a whole word or idea, either concrete or abstract, in a single sign) and phonograms (representing either an alphabetic sound or a group of consonants), [the writing system] was used in formal inscriptions on tomb and temple walls as well as on elaborate funerary papyri. For everyday purposes, however, scribes used a shorthand version of the hieroglyphic script known as hieratic, which was quicker to write and more economical of space. The two writings existed side by side for at least 2,500 years.\n\nScraps of ancient hieratic writing, mostly penned by student scribes on limestone flakes called ostraca, suggest that no matter how humble his origins, an educated Egyptian could achieve almost anything. Horemheb (d.1292 B.C.) is a good example. Born of middle-ranking parents, his scribal training led to an army career. From Scribe of Recruits, during the reign of Akhenaten (1353–1336 B.C.), Horemheb rose through the military ranks and, by the rule of Tutankhamun (1332–1323 B.C.), he was commander in chief of the Egyptian forces. As a close adviser of the young Pharaoh, Horemheb was appointed “Deputy of the King throughout the Two Lands,” and might have expected to succeed to the throne should the king die childless. He had to wait a few years, but eventually Horemheb achieved the pinnacle of his career by becoming the last king of the 18th Dynasty, making his mark by instituting dramatic reforms to the organisation of the army, the judiciary and administration in general. The lasting success of these changes owed much to his scribal background. . . .\n\nBut education was not available to all. Government departments and major temples supported schools, where boys commenced their training at six or seven, sometimes earlier. To these boarding establishments . . . family or household servants delivered the students’ food and drink rations daily for several years, during which time the student was not contributing to the family’s income. Boys from poorer families could only hope to be educated with support from a wealthier relative or patron, or through apprenticeship to an older scribe, perhaps the local clerk or land agent, who would teach them the basics of the scribe’s craft. This limited the scope for employment but such “on the job” training allowed apprentices to help out at home while learning. . . .\n\nScribal education began with the elementary principles of the hieratic script. The lowliest scribes, who trained for just five or six years, probably learned only the rudiments of the hieroglyphic script. Students were set exemplar documents and extracts from popular texts to copy, to practice their hieratic handwriting on basic-format letters, reports and contracts, while absorbing the good advice contained in the texts. Surviving examples of copy-work sometimes include tutors’ corrections added in red. Some significant Egyptian literary works survive almost exclusively from student copies.\n\nA schoolboy “dictionary” of hieroglyphs with their hieratic equivalents shows that a knowledge of more than 450 signs was required for everyday writing purposes. Lessons in record-keeping and filing and labelling enabled any half-competent scribe to perform that most essential of all scribal functions: the making and updating of lists. For professions such as those of government official, priest or lawyer, a scribe would train for several more years, increasing his vocabulary to perhaps a thousand or more signs. Those with the best handwriting or drawing skills might follow the craft of creating beautifully illustrated copies of funerary texts, commonly called Books of the Dead. Others could become draughtsmen, artists or architects. Doctors compiled their own collections of medication recipes, treatments and associated incantations, many copied from texts found in the House of Life, the temple library. Lawyers had to be familiar with the corpus of civil and religious laws and precedents found in the official records, which were administered by archivists. Egypt’s bureaucratic society depended on the skills of an army of scribes of all ranks from filing clerk to tax assessor. For young Egyptians, “be a scribe” was the best of career advice.";

const scribeLikeAnEgyptianQuestions: ExamQuestion[] = [
  {
    "id": "scribe-like-an-egyptian-1",
    "points": 1,
    "prompt": "Which sentence from the excerpt best supports the idea that there were different levels of education for a scribe?",
    "topic": "Central Idea & Theme",
    "choices": [
      {
        "id": "A",
        "text": "“However, contrary to popular belief, not all Egyptian scribes understood hieroglyphs.” (paragraph 1)"
      },
      {
        "id": "B",
        "text": "“For everyday purposes, however, scribes used a shorthand version of the hieroglyphic script known as hieratic, which was quicker to write and more economical of space.” (paragraph 2)"
      },
      {
        "id": "C",
        "text": "“This limited the scope for employment but such ‘on the job’ training allowed apprentices to help out at home while learning.” (paragraph 4)"
      },
      {
        "id": "D",
        "text": "“For professions such as those of government official, priest or lawyer, a scribe would train for several more years, increasing his vocabulary to perhaps a thousand or more signs.” (paragraph 6)"
      }
    ],
    "correctChoiceId": "D",
    "type": "multiple_choice"
  },
  {
    "id": "scribe-like-an-egyptian-2",
    "points": 1,
    "prompt": "Read this sentence from paragraph 2.\n\nIncluding both ideograms (which convey a whole word or idea, either concrete or abstract, in a single sign) and phonograms (representing either an alphabetic sound or a group of consonants), [the writing system] was used in formal inscriptions on tomb and temple walls as well as on elaborate funerary papyri.\n\nThe author’s purpose for including the sentence is to",
    "topic": "Central Idea & Theme",
    "choices": [
      {
        "id": "A",
        "text": "explain that hieroglyphs were reserved for royal and religious purposes."
      },
      {
        "id": "B",
        "text": "demonstrate the methods experts use to interpret hieroglyphs."
      },
      {
        "id": "C",
        "text": "clarify the significance of hieroglyphs in language and literature."
      },
      {
        "id": "D",
        "text": "describe the basic features of hieroglyphs and how they were typically used."
      }
    ],
    "correctChoiceId": "D",
    "type": "multiple_choice"
  },
  {
    "id": "scribe-like-an-egyptian-3",
    "points": 1,
    "prompt": "Which statement summarizes the process that schools used to train scribes?",
    "topic": "Central Idea & Theme",
    "choices": [
      {
        "id": "A",
        "text": "Boys had to memorize around 450 hieratic signs. Once they had learned these, they were expected to copy literary texts that contained valuable lessons."
      },
      {
        "id": "B",
        "text": "Boys spent at least five years learning hieratic signs, which they practiced by copying texts. During this period, they were also introduced to basic hieroglyphs."
      },
      {
        "id": "C",
        "text": "Boys spent five or six years learning the basics of hieratic script. After this period, they could become apprentices and begin learning hieroglyphics."
      },
      {
        "id": "D",
        "text": "Boys were taught two different scripts. They practiced both types by copying lists and eventually progressed to writing letters, reports, and contracts."
      }
    ],
    "correctChoiceId": "B",
    "type": "multiple_choice"
  },
  {
    "id": "scribe-like-an-egyptian-4",
    "points": 1,
    "prompt": "Which claim is best supported by the information presented in paragraphs 3 and 4?",
    "topic": "Central Idea & Theme",
    "choices": [
      {
        "id": "A",
        "text": "Education was difficult for the common citizens of Egypt to obtain."
      },
      {
        "id": "B",
        "text": "Once students began studying to become scribes, their future held more possibilities."
      },
      {
        "id": "C",
        "text": "If someone wanted to become a scribe, support from outside sources such as the government or a temple was necessary."
      },
      {
        "id": "D",
        "text": "Becoming a successful scribe required a student’s family to sacrifice time and money in order to ensure the best education."
      }
    ],
    "correctChoiceId": "B",
    "type": "multiple_choice"
  },
  {
    "id": "scribe-like-an-egyptian-5",
    "points": 1,
    "prompt": "Hieratic script was particularly valuable in a bureaucratic government because",
    "topic": "Central Idea & Theme",
    "choices": [
      {
        "id": "A",
        "text": "using hieratic script was an efficient way for scribes to produce large amounts of documentation."
      },
      {
        "id": "B",
        "text": "many members of the general public could comprehend information that was written in hieratic script."
      },
      {
        "id": "C",
        "text": "knowledge of hieratic script prepared scribes to serve their society in increasingly challenging roles."
      },
      {
        "id": "D",
        "text": "people from different professional backgrounds could easily communicate with one another in hieratic script."
      }
    ],
    "correctChoiceId": "A",
    "type": "multiple_choice"
  },
  {
    "id": "scribe-like-an-egyptian-6",
    "points": 1,
    "prompt": "The diagram after paragraph 6 best provides additional support for the topic of the excerpt by",
    "topic": "Central Idea & Theme",
    "choices": [
      {
        "id": "A",
        "text": "demonstrating the place of scribes in ancient Egyptian social structure."
      },
      {
        "id": "B",
        "text": "depicting the types of tasks performed by each social class."
      },
      {
        "id": "C",
        "text": "indicating that scribes were able to easily improve their social ranking."
      },
      {
        "id": "D",
        "text": "comparing the social positions of each social class in ancient Egypt."
      }
    ],
    "correctChoiceId": "A",
    "type": "multiple_choice"
  },
  {
    "id": "scribe-like-an-egyptian-7",
    "points": 1,
    "prompt": "Based on the excerpt, which statement would the author most strongly agree with?",
    "topic": "Central Idea & Theme",
    "choices": [
      {
        "id": "A",
        "text": "Boys in Egypt were encouraged to enter the same profession as older male relatives."
      },
      {
        "id": "B",
        "text": "Knowledge of hieroglyphs was helpful to Egyptians who were interested in becoming scribes."
      },
      {
        "id": "C",
        "text": "Hieratic script was more practical to ancient Egyptians than hieroglyphs were."
      },
      {
        "id": "D",
        "text": "Boys in Egypt who studied for only a few years were unlikely to find employment as scribes."
      }
    ],
    "correctChoiceId": "C",
    "type": "multiple_choice"
  }
];

export const scribeLikeAnEgyptianPassageSet: ExamPassageSet = {
  id: "ela-scribe-like-an-egyptian",
  questionCount: scribeLikeAnEgyptianQuestions.length,
  directions: {
  "subject": "English Language Arts",
  "title": "READING COMPREHENSION",
  "breadcrumbLabel": "ELA RDG COMP DIRECTIONS",
  "body": "Read each text and answer the related questions. Base your answers only on the content within the text."
},
  passage: createProsePassage({
    id: "scribe-like-an-egyptian",
    passageType: "informational",
    title: "Excerpt from “Scribe Like an Egyptian”",
    image: {"alt":"Excerpt from “Scribe Like an Egyptian” illustration","src":"/exam-images/scribe-like-an-egyptian-passage.png"},
    sourceNote: "From “Scribe Like an Egyptian” by Hilary Wilson from HISTORY TODAY, August 8, 2019. Copyright © 2019 by History Today Ltd. Company.",
    text: scribeLikeAnEgyptianPassageText,
  }),
  questions: scribeLikeAnEgyptianQuestions,
};
