import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { canonicalElaTopic, labElaTopics } from "../../../server/src/shared/questionBank";
import { teacherPlanClient } from "../lib/api";
import { assignmentDay, forecast, isOverdue, statusLabels, todayInNewYork, weekDays, type AssignmentDraft, type AssignmentPage, type ContentHistory, type PlanAssignment, type PlanClient, type PlanContent, type PlanOverview, type PlanSettings } from "../lib/learningPlan";
import "../styles/learning-plan.css";
import { PASSAGE_CATEGORIES, passageCategoryLabel } from "../../../server/src/shared/passageCategories";
import { categoryInventory, filterContentInventory, passageCompletionDate, passageSource, type PassageCompletionFilter, type ContentInventory } from "../lib/passageOrganization";

export type PlanView = "summary" | "plan" | "content" | "schedule" | "history";
const date = (value: string | null | undefined) => value ? value.length === 10 ? value : todayInNewYork(new Date(value)) : "—";
const kindLabel: Record<string, string> = { passage: "Passage", practice: "Skill practice", exam: "Exam", external: "External", offline: "Offline / custom" };
const errorMessage = (error: unknown) => error instanceof Error ? error.message : "Could not save. Please try again.";
const blankDraft = (): AssignmentDraft => ({ kind: "external", title: "", instructions: "", url: "", status: "assigned", dueDate: null, plannedDate: null, estimatedMinutes: null, questionTarget: null });

function PlanningSettings({ settings, remaining, onSave }: { settings: PlanSettings; remaining: number; onSave: (settings: PlanSettings) => Promise<void> }) {
  const [draft, setDraft] = useState(settings);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const estimate = forecast(remaining, draft.passagePace, draft.targetDate);
  async function save(event: FormEvent) {
    event.preventDefault(); setSaving(true); setMessage("");
    try { await onSave(draft); setMessage("Planning settings saved."); } catch (error) { setMessage(errorMessage(error)); } finally { setSaving(false); }
  }
  return <details className="lp-settings"><summary>Planning pace, target date & teacher-only notes</summary><form onSubmit={save}>
    <div className="lp-fields"><label>Passages per week<input min="0.1" max="100" step="0.1" type="number" value={draft.passagePace ?? ""} onChange={event => setDraft({ ...draft, passagePace: event.target.value ? Number(event.target.value) : null })} /></label>
      <label>Target date<input type="date" value={draft.targetDate ?? ""} onInput={event => setDraft({ ...draft, targetDate: event.currentTarget.value || null })} /></label></div>
    <p>{remaining} never-assigned passages · {estimate.weeksSupply === null ? "Set a pace to estimate supply" : `about ${estimate.weeksSupply} weeks of fresh material`}.</p>
    {estimate.weeksAvailable !== null && <p>{estimate.weeksAvailable.toFixed(1)} weeks to target · {estimate.needed === null ? "Set a pace to calculate need." : `${estimate.needed} passages needed at this pace · ${estimate.difference! >= 0 ? `${estimate.difference} surplus` : `${-estimate.difference!} additional passages needed`}`}</p>}
    <small>Supply = never-assigned passages ÷ your pace. Need = weeks until target × pace, rounded up. Planned reservations are excluded from fresh supply. No duration or exam date is inferred.</small>
    <label>Teacher-only planning notes<textarea rows={3} maxLength={20000} value={draft.teacherNotes} onChange={event => setDraft({ ...draft, teacherNotes: event.target.value })} /></label>
    <footer><button disabled={saving} type="submit">{saving ? "Saving…" : "Save planning settings"}</button><small>Last saved: {date(settings.updatedAt)} · Never shown to students.</small></footer>{message && <p role="status">{message}</p>}
  </form></details>;
}

export function TeacherLearningPlan({ accessToken, studentId, studentName, view, onView, skillFilter, onSkillFilter, sourceCategory = "", onSourceCategory, onInventory, client: injectedClient }: {
  accessToken: string; studentId: string; studentName: string; view: PlanView; onView: (view: PlanView) => void; skillFilter: string; onSkillFilter: (skill: string) => void; client?: PlanClient;
  sourceCategory?: string; onSourceCategory?: (category: string) => void; onInventory?: (inventory: ContentInventory) => void;
}) {
  const client = useMemo(() => injectedClient ?? teacherPlanClient(accessToken, studentId), [injectedClient, accessToken, studentId]);
  const [overview, setOverview] = useState<PlanOverview | null>(null);
  const [list, setList] = useState<AssignmentPage | null>(null);
  const [revision, setRevision] = useState(0);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState("active");
  const [page, setPage] = useState(0);
  const [search, setSearch] = useState("");
  const [contentStatus, setContentStatus] = useState("Never assigned");
  const targetedEla = labElaTopics.includes(canonicalElaTopic(skillFilter));
  const [contentCompletion, setContentCompletion] = useState<PassageCompletionFilter>("");
  const [contentKind, setRawContentKind] = useState(targetedEla ? "practice" : skillFilter ? "" : "passage");
  const [category, setCategory] = useState("");
  const [localSourceCategory, setLocalSourceCategory] = useState("");
  const selectedSourceCategory = onSourceCategory ? sourceCategory : localSourceCategory;
  const setSourceCategory = onSourceCategory ?? setLocalSourceCategory;
  const [subject, setSubject] = useState(targetedEla ? "English" : "");
  const [contentSource, setContentSource] = useState(targetedEla ? "SHSAT Lab" : "");
  const setContentKind = (kind: string) => { setRawContentKind(kind); setContentCompletion(""); if (kind === "passage") setContentSource(""); };
  const [contentSort, setContentSort] = useState("title");
  const [contentDirection, setContentDirection] = useState<"asc" | "desc">("asc");
  const [selected, setSelected] = useState<string[]>([]);
  const [weekOffset, setWeekOffset] = useState(0);
  const [weekTasks, setWeekTasks] = useState<PlanAssignment[]>([]);
  const [weekTotal, setWeekTotal] = useState(0);
  const [editor, setEditor] = useState<{ draft: AssignmentDraft; contents: PlanContent[]; existing?: PlanAssignment; batchId: string } | null>(null);
  const [repeatWarning, setRepeatWarning] = useState<string[]>([]);
  const [detail, setDetail] = useState<PlanAssignment | null>(null);
  const [history, setHistory] = useState<{ content: PlanContent; data: ContentHistory; page: number } | null>(null);
  const editorDialog = useRef<HTMLDialogElement>(null);
  const detailDialog = useRef<HTMLDialogElement>(null);
  const historyDialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { let active = true; client.overview().then(data => { if (active) { setOverview(data); onInventory?.(data.inventory ?? []); setError(""); } }).catch(error => { if (active) setError(errorMessage(error)); }); return () => { active = false; }; }, [client, revision, onInventory]);
  const listStatus = view === "history" ? "all" : status;
  useEffect(() => { if (!["plan", "history"].includes(view)) return; let active = true; client.list(listStatus, page, search).then(data => { if (active) setList(data); }).catch(error => { if (active) setError(errorMessage(error)); }); return () => { active = false; }; }, [client, view, listStatus, page, search, revision]);
  useEffect(() => { if (view !== "schedule") return; let active = true; client.list("schedule", weekOffset).then(data => { if (active) { setWeekTasks(data.assignments); setWeekTotal(data.total); } }).catch(error => { if (active) setError(errorMessage(error)); }); return () => { active = false; }; }, [client, view, weekOffset, revision]);
  useEffect(() => { if (editor) editorDialog.current?.showModal(); }, [editor]);
  useEffect(() => { if (detail) detailDialog.current?.showModal(); }, [detail]);
  useEffect(() => { if (history) historyDialog.current?.showModal(); }, [history]);
  const refresh = () => setRevision(value => value + 1);
  const inventory = overview?.inventory ?? [];
  const passages = inventory.filter(row => row.content.kind === "passage");
  const remaining = passages.filter(row => row.status === "Never assigned").length;
  const visibleContent = useMemo(() => filterContentInventory(overview?.inventory ?? [], { kind: contentKind, status: contentStatus, completion: contentCompletion, genre: category, category: selectedSourceCategory, source: contentSource, subject, skill: canonicalElaTopic(skillFilter), search, sort: contentSort, direction: contentDirection }), [overview, contentKind, contentStatus, contentCompletion, category, selectedSourceCategory, contentSource, subject, skillFilter, search, contentSort, contentDirection]);
  const categoryCounts = useMemo(() => categoryInventory(overview?.inventory ?? []), [overview]);
  const passageMetadata = useMemo(() => new Map(overview?.catalog.filter(content => content.kind === "passage" || content.contentSource).map(content => [content.id, `${content.subject} · ${content.contentSource || passageCategoryLabel(content.passageCategory)}`])), [overview]);
  const assignmentMetadata = (item: PlanAssignment) => item.contentId ? passageMetadata.get(item.contentId) : undefined;
  const clearContentFilters = () => { setContentCompletion(""); setContentStatus(""); setContentKind("passage"); setCategory(""); setSourceCategory(""); setContentSource(""); setSubject(""); onSkillFilter(""); setSearch(""); setSelected([]); };
  async function act(item: PlanAssignment, changes: Partial<PlanAssignment>) {
    setBusy(true); setNotice("");
    try { await client.update(item.id, item.revision, changes); refresh(); if (history) setHistory({ ...history, data: await client.history(history.content.kind, history.content.id, history.page) }); setNotice("Assignment updated; history retained."); } catch (error) { setNotice(errorMessage(error)); } finally { setBusy(false); }
  }
  function openEditor(contents: PlanContent[] = [], planned = false, existing?: PlanAssignment) {
    historyDialog.current?.close();
    setRepeatWarning([]); setNotice("");
    const warnings = contents.flatMap(content => { const row = inventory.find(row => row.content.id === content.id && row.content.kind === content.kind); return row && row.status !== "Never assigned" ? [`${content.title}: ${row.status} · Last activity ${date(row.lastActivity)}${row.dueDate ? ` · Due ${row.dueDate}` : ""} · ${row.assignmentCount} assignment records · ${row.priorCount} saved attempts/results`] : []; });
    if (!existing) setRepeatWarning(warnings);
    setEditor({ contents, existing, batchId: crypto.randomUUID(), draft: existing ? { ...existing, status: existing.status === "planned" ? "planned" : "assigned" } : { ...blankDraft(), kind: contents[0]?.kind ?? "external", contentId: contents[0]?.id, status: planned ? "planned" : "assigned" } });
  }
  async function saveEditor(event?: FormEvent, allowRepeat = false) {
    event?.preventDefault(); if (!editor) return;
    if (repeatWarning.length && !allowRepeat && !editor.existing) return;
    setBusy(true); setNotice("");
    try {
      if (editor.existing) await client.update(editor.existing.id, editor.existing.revision, { ...editor.draft, status: editor.existing.status });
      else await client.create(editor.contents.length ? editor.contents.map(content => ({ ...editor.draft, kind: content.kind, contentId: content.id })) : [editor.draft], editor.batchId, allowRepeat);
      editorDialog.current?.close(); setSelected([]); setSearch(""); setPage(0); if (!editor.existing) { setStatus(editor.draft.status === "planned" ? "planned" : "active"); if (!editor.contents.length) onView("plan"); } refresh(); setNotice(editor.existing ? "Assignment updated." : "Added to this student's plan.");
    } catch (error) {
      const message = errorMessage(error); setNotice(message);
      if (message.includes("already received") || message.includes("already") && message.includes("planned")) setRepeatWarning([message]);
    } finally { setBusy(false); }
  }
  async function openDetail(item: PlanAssignment) { try { const data = await client.detail(item.id); historyDialog.current?.close(); setDetail(data); } catch (error) { setNotice(errorMessage(error)); } }
  async function openHistory(content: PlanContent, page = 0) { try { setHistory({ content, page, data: await client.history(content.kind, content.id, page) }); } catch (error) { setNotice(errorMessage(error)); } }
  const statusChip = (item: PlanAssignment) => <span className={`lp-chip is-${isOverdue(item) ? "overdue" : item.status}`}>{isOverdue(item) ? "Overdue · " : ""}{statusLabels[item.status]}</span>;
  const taskRows = (items: PlanAssignment[]) => items.map(item => <tr key={item.id}><td><button className="lp-link" onClick={() => openDetail(item)} type="button">{item.title}</button><small>{assignmentMetadata(item) || kindLabel[item.kind]}{item.completion ? ` · ${item.completion.source === "teacher" ? "Teacher verified" : "Saved platform work"}${item.completion.total ? ` · ${item.completion.correct}/${item.completion.total}` : ""}` : ""}</small></td><td>{statusChip(item)}</td><td>{date(item.assignedAt)}</td><td>{item.status === "planned" ? date(item.plannedDate) : date(item.dueDate)}</td><td>{item.estimatedMinutes === null ? "—" : `${item.estimatedMinutes} min`}</td><td><div className="lp-row-actions"><button disabled={busy} onClick={() => openEditor([], false, item)} type="button">Edit</button>{item.status === "planned" && <button disabled={busy} onClick={() => act(item, { status: "assigned" })} type="button">Assign now</button>}{!["completed", "cancelled", "skipped"].includes(item.status) && <>{item.status !== "planned" && <button disabled={busy} onClick={() => act(item, { status: "completed" })} type="button">Verify complete</button>}<button disabled={busy} onClick={() => act(item, { status: "cancelled" })} type="button">Cancel task</button><button disabled={busy} onClick={() => act(item, { status: "skipped" })} type="button">Skip</button></>}</div></td></tr>);
  return <section className="lp-workspace" aria-label={`${studentName} personalized learning plan`}>
    <header className="lp-heading"><div><h3>Personalized learning plan</h3><small>Only {studentName}'s assignments, reservations, and history.</small></div><div><button onClick={() => openEditor()} type="button">+ Add homework</button>{view === "summary" && <button onClick={() => onView("plan")} type="button">View full plan →</button>}</div></header>
    {error && <p className="lp-error" role="alert">{error} <button onClick={refresh} type="button">Retry</button></p>}
    {notice && <p role="status">{notice}</p>}
    {!overview && !error && <p>Loading this student's plan…</p>}
    {overview && <>
      <div className="lp-summary-strip">{[["Assigned / working", overview.summary.assigned], ["Planned", overview.summary.planned], ["Overdue", overview.summary.overdue], ["Completed this week", overview.summary.completedThisWeek]].map(([label, value]) => <span key={label}><small>{label}</small><strong>{value}</strong></span>)}<span><small>Fresh passages</small><strong>{remaining}<button onClick={() => { setContentStatus("Never assigned"); setContentKind("passage"); setCategory(""); setSourceCategory(""); setSubject(""); setSearch(""); onSkillFilter(""); setSelected([]); onView("content"); }} type="button">Browse →</button></strong></span></div>
      {view === "summary" && <div className="lp-upcoming">{overview.summary.upcoming.length ? overview.summary.upcoming.slice(0, 3).map(item => <button key={item.id} onClick={() => { onView("plan"); setStatus(item.status === "planned" ? "planned" : "active"); setPage(0); }} type="button"><span>{item.title}</span>{statusChip(item)}<small>{assignmentDay(item) ? `${item.status === "planned" ? "Planned" : "Due"} ${assignmentDay(item)}` : "No date set"}</small></button>) : <p>No upcoming homework. Add a task or reserve content for later.</p>}</div>}
      {view !== "summary" && overview.settings && <PlanningSettings key={overview.settings.revision} settings={overview.settings} remaining={remaining} onSave={async settings => { await client.settings(settings); refresh(); setNotice("Planning settings saved."); }} />}
      {view === "summary" && <p>{overview.summary.dueThisWeek} due this week · {overview.summary.knownMinutes} known scheduled minutes ({overview.summary.timed}/{overview.summary.weekly} tasks have estimates){overview.settings?.passagePace ? ` · ${overview.settings.passagePace} passages/week → about ${forecast(remaining, overview.settings.passagePace, overview.settings.targetDate).weeksSupply} weeks of fresh supply` : " · Set a passage pace in Learning plan to forecast supply"}</p>}
      {(view === "plan" || view === "history") && <>
        <div className="lp-toolbar">{view === "plan" && <label>Show<select value={status} onChange={event => { setStatus(event.target.value); setPage(0); }}>{[["active", "Current work"], ["planned", "Planned / reserved"], ["overdue", "Overdue"], ["review", "Awaiting review"], ["completed", "Completed"], ["cancelled", "Cancelled"], ["skipped", "Skipped"], ["all", "All history"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>}<label>Search assignments<input value={search} onChange={event => { setSearch(event.target.value); setPage(0); }} /></label><small>{list?.total ?? 0} matching tasks · Completed work remains in history.</small></div>
        <div className="lp-table-scroll"><table><thead><tr><th>Assignment / source</th><th>Status</th><th>Assigned</th><th>Due / planned</th><th>Estimate</th><th>Actions</th></tr></thead><tbody>{taskRows(list?.assignments ?? [])}</tbody></table></div>{list?.assignments.length === 0 && <p>No assignments in this view.</p>}
        <footer><button disabled={page === 0} onClick={() => setPage(value => value - 1)} type="button">Previous tasks</button><span>Page {page + 1} · 50 per page</span><button disabled={!list || (page + 1) * 50 >= list.total} onClick={() => setPage(value => value + 1)} type="button">Next tasks</button></footer>
      </>}
      {view === "content" && <>
        <div className="lp-inventory-summary">{["Completed", "Assigned", "In progress", "Awaiting review", "Planned", "Previously assigned", "Never assigned"].map(value => <button key={value} onClick={() => setContentStatus(value)} type="button">{value} <b>{passages.filter(row => row.status === value).length}</b></button>)}<small>{passages.length} eligible passages · Unique current statuses; repeat assignments stay in history.</small></div>
        <div className="lp-toolbar">
          <label>Content<select value={contentKind} onChange={event => { setContentKind(event.target.value); setSelected([]); }}><option value="passage">English passages</option><option value="practice">Skill practice</option><option value="exam">Exams</option><option value="">All content</option></select></label>
          <label>Subject<select value={subject} onChange={event => setSubject(event.target.value)}><option value="">All subjects</option><option>English</option><option>Math</option><option>English + Math</option></select></label>
          <label>Content source<select value={contentSource} onChange={event => { setContentSource(event.target.value); setSelected([]); }}><option value="">All sources</option><option>SHSAT Lab</option>{[...new Set(overview.catalog.map(content => content.contentSource).filter((value): value is string => Boolean(value) && value !== "SHSAT Lab"))].map(value => <option key={value}>{value}</option>)}</select></label>
          {contentKind === "passage" && <label>Passage completion<select value={contentCompletion} onChange={event => { setContentCompletion(event.target.value as PassageCompletionFilter); setContentStatus(""); setSelected([]); }}><option value="">All passages</option><option value="completed">Completed passages</option><option value="not_completed">Not yet completed</option></select></label>}
          <label>Passage category<select value={selectedSourceCategory} onChange={event => setSourceCategory(event.target.value)}><option value="">All categories</option>{PASSAGE_CATEGORIES.map(value => <option key={value.value} value={value.value}>{value.label}</option>)}</select></label>
          <label>History status<select value={contentStatus} onChange={event => setContentStatus(event.target.value)}><option value="">All statuses</option>{["Never assigned", "Planned", "Assigned", "In progress", "Awaiting review", "Completed", "Previously assigned"].map(value => <option key={value}>{value}</option>)}</select></label>
          <label>Type / genre<select value={category} onChange={event => setCategory(event.target.value)}><option value="">All types</option>{[...new Set(overview.catalog.map(content => content.category))].sort().map(value => <option key={value}>{value}</option>)}</select></label>
          <label>Skill<select value={skillFilter} onChange={event => onSkillFilter(event.target.value)}><option value="">All skills</option>{[...new Set(overview.catalog.flatMap(content => content.skills))].sort().map(skill => <option key={skill}>{skill}</option>)}</select></label>
          <label>Find content<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Title, version or skill" /></label>
          <label>Sort by<select value={contentSort} onChange={event => setContentSort(event.target.value)}><option value="title">Title</option><option value="category">Passage category</option><option value="activity">Last recorded activity</option><option value="questions">Question count</option><option value="unassigned">Never assigned</option></select></label>
          <label>Direction<select value={contentDirection} onChange={event => setContentDirection(event.target.value as "asc" | "desc")}><option value="asc">{contentSort === "title" || contentSort === "category" ? "A–Z" : contentSort === "activity" ? "Oldest first" : "Fewest first"}</option><option value="desc">{contentSort === "title" || contentSort === "category" ? "Z–A" : contentSort === "activity" ? "Newest first" : "Most first"}</option></select></label>
          <button onClick={clearContentFilters} type="button">Clear filters</button>
          {contentSource === "SHSAT Lab" && <a href={`http://127.0.0.1:4319/?bankTopic=${encodeURIComponent(canonicalElaTopic(skillFilter))}#question-bank`} target="_blank" rel="noreferrer">Build a matching set in the local Content Editor →</a>}
        </div>
        <div className="lp-toolbar"><strong>{visibleContent.length} matching items · {selected.length} selected</strong><button disabled={!selected.length} onClick={() => openEditor(overview.catalog.filter(content => selected.includes(`${content.kind}:${content.id}`)))} type="button">Assign selected</button><button disabled={!selected.length} onClick={() => openEditor(overview.catalog.filter(content => selected.includes(`${content.kind}:${content.id}`)), true)} type="button">Plan selected / reserve</button><button onClick={() => setSelected([])} type="button">Clear selection</button></div>
        <div className="lp-table-scroll"><table><thead><tr><th>Select</th><th>Content / category</th><th>Source / version</th><th>Status for {studentName}</th><th>Questions / skills</th><th>Last completed</th><th>Last activity</th><th>Actions</th></tr></thead><tbody>{visibleContent.map(row => { const key = `${row.content.kind}:${row.content.id}`; return <tr key={key}><td><input aria-label={`Select ${row.content.title}${row.content.versionLabel ? ` — ${row.content.versionLabel}` : ""}`} type="checkbox" checked={selected.includes(key)} disabled={!selected.includes(key) && selected.length >= 30} onChange={event => setSelected(values => event.target.checked ? [...values, key] : values.filter(value => value !== key))} /></td><td><button className="lp-link" onClick={() => openHistory(row.content)} type="button">{row.content.title}</button><small>{row.content.subject}{row.content.kind === "passage" ? ` · ${passageCategoryLabel(row.content.passageCategory)}` : ` · ${kindLabel[row.content.kind]}`}</small><small>{row.content.category}</small></td><td>{row.content.kind === "passage" ? passageSource(row.content) : row.content.contentSource || "No Data"}</td><td><span className="lp-chip">{row.status}</span><small>{row.dueDate ? `Due ${row.dueDate}` : row.plannedDate ? `Planned ${row.plannedDate}` : ""}</small></td><td>{row.content.questionCount}<small>{row.content.skills.join(" · ")}</small></td><td>{passageCompletionDate(row.lastCompletedAt)}</td><td>{date(row.lastActivity)}<small>{row.assignmentCount} tasks · {row.priorCount} existing results</small></td><td><div className="lp-row-actions"><button onClick={() => openEditor([row.content])} type="button">Assign</button><button onClick={() => openEditor([row.content], true)} type="button">Plan</button></div></td></tr>; })}</tbody></table></div>{!visibleContent.length && <p>No {contentStatus ? contentStatus.toLowerCase() : "matching"} {selectedSourceCategory ? passageCategoryLabel(selectedSourceCategory) + " " : ""}content for {studentName} matches these filters. <button onClick={clearContentFilters} type="button">Clear filters</button><button onClick={() => setContentStatus("Completed")} type="button">Show completed</button></p>}
        <div className="lp-category-counts" aria-label="English passage inventory by source">{categoryCounts.map(value => <button key={value.value} onClick={() => { setSourceCategory(value.value); setContentStatus("Never assigned"); setContentKind("passage"); setCategory(""); setSubject("English"); setSearch(""); onSkillFilter(""); }} type="button"><strong>{value.label}</strong><span>{value.remaining} remaining · {value.used}/{value.total} used · {value.completed} completed</span><small>{value.assigned} assigned / working · {value.planned} planned</small></button>)}</div>
        <small>Counts are unique passages, not attempts. “Used” means issued or completed; planned-only reservations are not used. Completed includes earlier results even when a repeat assignment is active.</small>
      </>}
      {view === "schedule" && <>
        {weekTotal > weekTasks.length && <p role="status">Showing {weekTasks.length} of {weekTotal} scheduled tasks. Use the task list to inspect the rest.</p>}
        <div className="lp-toolbar"><button onClick={() => setWeekOffset(value => value - 1)} type="button">Previous week</button><strong>Week of {weekDays(todayInNewYork(), weekOffset)[0]}</strong><button onClick={() => setWeekOffset(value => value + 1)} type="button">Next week</button><button onClick={() => setWeekOffset(0)} type="button">This week</button><small>{weekTasks.length} scheduled tasks · {weekTasks.filter(item => item.estimatedMinutes !== null).reduce((sum, item) => sum + item.estimatedMinutes!, 0)} known minutes ({weekTasks.filter(item => item.estimatedMinutes !== null).length}/{weekTasks.length} estimates recorded)</small></div>
        <div className="lp-week-grid">{weekDays(todayInNewYork(), weekOffset).map(day => { const items = weekTasks.filter(item => assignmentDay(item) === day); return <section key={day}><header>{new Date(`${day}T12:00:00Z`).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", timeZone: "UTC" })}<small>{items.length} tasks</small></header>{items.map(item => <button key={item.id} onClick={() => openDetail(item)} type="button"><strong>{item.title}</strong>{statusChip(item)}<small>{item.estimatedMinutes === null ? "No time estimate" : `${item.estimatedMinutes} min`}</small></button>)}{!items.length && <p>No scheduled work</p>}</section>; })}</div><small>Tasks without a due/planned date remain in the task list. The week is Monday–Sunday in America/New_York. Only teacher-entered duration estimates are counted.</small>
      </>}
    </>}
    <dialog ref={editorDialog} className="lp-dialog" aria-labelledby="lp-editor-title" onClose={() => setEditor(null)}>{editor && <><header><h3 id="lp-editor-title">{editor.existing ? "Edit homework" : editor.draft.status === "planned" ? "Plan / reserve work" : "Assign homework"} · {studentName}</h3><button autoFocus onClick={() => editorDialog.current?.close()} type="button">Close homework editor</button></header><form onSubmit={event => saveEditor(event)}>
      {editor.contents.length ? <p>{editor.contents.map(content => content.title).join(" · ")}</p> : editor.existing?.contentId ? <strong>{editor.existing.title}</strong> : <><label>Homework type<select value={editor.draft.kind} onChange={event => setEditor({ ...editor, draft: { ...editor.draft, kind: event.target.value as AssignmentDraft["kind"] } })}><option value="external">External website</option><option value="offline">Offline / custom task</option></select></label><label>Title<input required maxLength={300} value={editor.draft.title ?? ""} onChange={event => setEditor({ ...editor, draft: { ...editor.draft, title: event.target.value } })} /></label><label>External URL (optional)<input type="url" value={editor.draft.url ?? ""} placeholder="https://… or leave blank" onChange={event => setEditor({ ...editor, draft: { ...editor.draft, url: event.target.value || null } })} /></label></>}
      {!editor.existing && <label>Publish state<select value={editor.draft.status} onChange={event => setEditor({ ...editor, draft: { ...editor.draft, status: event.target.value as "assigned" | "planned" } })}><option value="assigned">Assign now — visible to student</option><option value="planned">Planned / reserved — teacher only</option></select></label>}
      <div className="lp-fields"><label>Due date (optional)<input type="date" value={editor.draft.dueDate ?? ""} onInput={event => setEditor({ ...editor, draft: { ...editor.draft, dueDate: event.currentTarget.value || null } })} /></label><label>Planned date (optional)<input type="date" value={editor.draft.plannedDate ?? ""} onInput={event => setEditor({ ...editor, draft: { ...editor.draft, plannedDate: event.currentTarget.value || null } })} /></label><label>Expected minutes per task (optional)<input type="number" min={1} max={10080} value={editor.draft.estimatedMinutes ?? ""} onChange={event => setEditor({ ...editor, draft: { ...editor.draft, estimatedMinutes: event.target.value ? Number(event.target.value) : null } })} /></label>{(editor.contents.some(content => content.kind === "practice" && content.practiceMode !== "bank_set") || editor.existing?.kind === "practice" && overview?.catalog.find(content => content.id === editor.existing?.contentId)?.practiceMode !== "bank_set") && <label>New practice questions to complete<input type="number" min={1} max={10000} disabled={Boolean(editor.existing?.assignedAt)} value={editor.draft.questionTarget ?? ""} onChange={event => setEditor({ ...editor, draft: { ...editor.draft, questionTarget: event.target.value ? Number(event.target.value) : null } })} /></label>}</div>
      <label>Student-visible instructions<textarea rows={4} maxLength={10000} value={editor.draft.instructions ?? ""} onChange={event => setEditor({ ...editor, draft: { ...editor.draft, instructions: event.target.value } })} /></label>
      <small>Publishing records the actual assigned time. Passages, exams, and saved question-bank sets use completed attempts. Regular topic practice counts new questions against its baseline. Other work is student-reported and teacher-verified. Blank planned dates reserve material for later.</small>
      {repeatWarning.length > 0 && <div className="lp-repeat-warning" role="alert"><strong>Previously used or reserved for this student</strong>{repeatWarning.map((message, index) => <p key={index}>{message}</p>)}<button disabled={busy} onClick={() => saveEditor(undefined, true)} type="button">{editor.draft.status === "planned" ? "Plan again" : "Assign again"} — intentional repeat</button><button onClick={() => editorDialog.current?.close()} type="button">Cancel repeat</button></div>}
      {notice && <p role="status">{notice}</p>}<footer><button disabled={busy || Boolean(repeatWarning.length && !editor.existing)} type="submit">{busy ? "Saving…" : editor.existing ? "Save homework changes" : editor.draft.status === "planned" ? "Save planned work" : "Assign to this student"}</button></footer>
    </form></>}</dialog>
    <dialog ref={detailDialog} className="lp-dialog" aria-labelledby="lp-detail-title" onClose={() => setDetail(null)}>{detail && <><header><h3 id="lp-detail-title">{detail.title}</h3><button autoFocus onClick={() => detailDialog.current?.close()} type="button">Close task details</button></header><div className="lp-dialog-body">{statusChip(detail)}<p style={{ whiteSpace: "pre-wrap" }}>{detail.instructions || "No additional instructions."}</p>{detail.url && <a href={detail.url} target="_blank" rel="noopener noreferrer">Open external resource ↗</a>}<p>Assigned {date(detail.assignedAt)} · Due {date(detail.dueDate)} · Planned {date(detail.plannedDate)} · Completed {date(detail.completedAt)}</p>{detail.completion && <p>Completion: {detail.completion.source} · {date(detail.completion.at)}{detail.completion.total ? ` · ${detail.completion.correct}/${detail.completion.total}` : ""}</p>}<button onClick={() => { const item = detail; detailDialog.current?.close(); openEditor([], false, item); }} type="button">Edit task / change dates</button><h4>Permanent task history</h4>{detail.events?.map((event, index) => <details key={index}><summary>{event.at.replace("T", " ").slice(0, 16)} · {event.action}</summary><pre>{JSON.stringify(event.changes, null, 2)}</pre></details>)}</div></>}</dialog>
    <dialog ref={historyDialog} className="lp-dialog" aria-labelledby="lp-content-history-title" onClose={() => setHistory(null)}>{history && <><header><h3 id="lp-content-history-title">{history.content.title} · {studentName}'s history</h3><button autoFocus onClick={() => historyDialog.current?.close()} type="button">Close content history</button></header><div className="lp-dialog-body"><div className="lp-table-scroll"><table><thead><tr><th>Assignment</th><th>Status</th><th>Assigned</th><th>Due / planned</th><th>Estimate</th><th>Actions</th></tr></thead><tbody>{taskRows(history.data.assignments)}</tbody></table></div>{history.data.assignments.length === 0 && <p>No assignment records for this student.</p>}<footer><button disabled={history.page === 0} onClick={() => openHistory(history.content, history.page - 1)} type="button">Previous history</button><button disabled={(history.page + 1) * 50 >= history.data.total} onClick={() => openHistory(history.content, history.page + 1)} type="button">Next history</button></footer><h4>Existing platform results</h4>{history.data.prior.map((activity, index) => <p key={index}>{activity.source} · {date(activity.at)}{activity.total ? ` · ${activity.correct}/${activity.total}` : ""}</p>)}<small>Earlier results prove content use, not when homework was assigned. No historical assignment dates are invented.</small></div></>}</dialog>
  </section>;
}
